/* For license and copyright information please see LEGAL file in repository */

package org

import (
	"../libgo/protocol"
)

// Voucher or gift voucher is a bond of the redeemable transaction type which is worth a certain monetary value and
// which may be spent only for specific reasons or on specific products
type Voucher interface {
	ID() [16]byte           // VoucherID
	Status() Voucher_Status //
	Time() protocol.Time    // Save time
	RequestID() [16]byte    // user-request domain
}

type Voucher_Status uint8

const (
	Voucher_Status_Unset   Voucher_Status = 0
	Voucher_Status_Blocked Voucher_Status = (1 << iota)
	Voucher_Status_Revoked
	Voucher_Status_AutoGenerated
)
